# .github/workflows/docker.yml
name: Docker Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    uses: jasperbruin/aws-ml-deployment/.github/workflows/docker-build-reusable.yml@main
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write